name: test
channels:
 - pytorch
 - conda-forge
dependencies:
 - python=3.7.12
 - cudatoolkit=11.1.1
 - cudatoolkit-dev=11.4.0
 - pytorch=1.8.0
 - torchaudio=0.8.0
 - jupyter
 - datasets
 - numpy=1.19.5
 - pandas=1.3.5
 - rdkit=2022.03.4
 - selfies=2.1.1
 - matplotlib
 - textdistance
 - tokenizers=0.9.4
 - transformers=4.2.1
 - seaborn=0.12.1
 - setuptools>=18.0
 - scipy
 - pip
variables:
  CUDA_HOME: /Data1/sungmin/anaconda3/envs/test/pkgs/cuda-toolkit