name: selfedit
channels:
 - pytorch
 - conda-forge
 - anaconda
dependencies:
 - python=3.7.12
 - cudatoolkit=11.1.1
 - cudatoolkit-dev=11.4.0
 - pytorch=1.8.0
 - jupyter
 - tqdm
 - datasets
 - numpy=1.19.5
 - pandas=1.3.5
 - rdkit=2022.03.4
 - selfies=2.1.1
 - matplotlib
 - textdistance
 - tokenizers=0.9.4
 - transformers=4.2.1
 - seaborn=0.12.1
 - setuptools>=18.0
 - scipy
 - scikit-learn=0.20.4
 - pip
 - pip:
   - git+https://github.com/sungmin630/SentEval.git
   - git+https://github.com/princeton-nlp/SimCSE.git
